### ISSUE TITLE
Upgrade Tomcat to 8

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/planetarydata.org#1]
Tomcat 7 has reached end of life so we must upgrade the Registry service of the International Planetary Data Alliance to use Tomcat 8.

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life , can you add an estimate for this ticket ? You can also change the status if it is done (you mentioned last stand up that you worked on that). Thanks

**Comment by nutjob4life** [comment]
Hi @tloubrieu-jpl: the estimate is 8 hours.

(I can't find this ticket on Zenhub otherwise I'd enter the estimate directly there.)

**Comment by jordanpadams** [comment]
@nutjob4life +1 you should see "Estimate" to the right below "Assignees" and "Labels". If not, you may need to install the Zenhub extension and/or sign-in. https://www.zenhub.com/extension

**Comment by nutjob4life** [comment]
@jordanpadams thanks. I had to unload and reload the extension on Chrome to get it to work. It's active now and I can see the estimate.

**Comment by nutjob4life** [comment]
This is now complete and testing shows good data from the IPDA registry and Tomcat 8.5.64
