### ISSUE TITLE
Complete URS request for review of website for DNS switch

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetarydata.org#12]

**Comment by jordanpadams** [comment]
URS315130 submitted. Awaiting approvla

**Comment by nutjob4life** [comment]
Quick FYI @jordanpadams we do have URS304382 and clearance CL#22-5090 for `planetarydata.org`. 

Maybe we request re-review of that? I don't know what the procedure is 🤷‍♀️

**Comment by jordanpadams** [comment]
@nutjob4life I referenced those in the new one, and I selected to check new content, vs a new site altogether.

**Comment by nutjob4life** [comment]
@jordanpadams copy that! 📡

**Comment by jordanpadams** [comment]
Done! URS315130 approved
