### ISSUE TITLE
Finalize website migration with DNS switch 

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetarydata.org#13]

**Comment by jordanpadams** [comment]
@nutjob4life can we get this wrapped up by end of sprint maybe?

**Comment by nutjob4life** [comment]
@jordanpadams let's do it. We'll need three things:

- The clearance number. We can get this from the URS, assuming it got to stage 5 "Approved for Unlimited Release". I think URS304382 is the older one. Wait a sec, found the one you submitted, URS315130 which has clearance № CL#23-2029
- The ASR number: 2164
- And a clean appscan. @jordanpadams did you request one? If not I will submit the request.

**Comment by nutjob4life** [comment]
DSIO-4405 filed

**Comment by nutjob4life** [comment]
@jordanpadams DSIO-4405 is marked as completed.

I tested visiting https://planetarydata.org/ and I end up at the new site.
