### ISSUE TITLE
Iterate on new planetarydata.org updates per feedback

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetarydata.org#15]
## 💡 Description

- [x] partner page - link to agency websites where possible
- [x] partner page - the logos are not really readable. may need different layout to actually see what they are
- [x] Add IPDA logo (from @edwardbarraza )
- [x] Link Contact Us to email PDS Help Desk and remove address info
- [x] Remove Social section
- [x] Add favicon (some simple planet image?)
- [x] ~Update theme to use fonts and color scheme from HDS (sent via email). contact @edwardbarraza for additional guidance.~
- [x] Update theme to use fonts and color scheme that are 508-compliant

**Comment by edwardbarraza** [comment]
[https://app.zenhub.com/files/349191592/bfc963a9-efea-46ed-ad7a-124ffa43d399/download](https://app.zenhub.com/files/349191592/bfc963a9-efea-46ed-ad7a-124ffa43d399/download)

Potential logos in the PDF above

**Comment by nutjob4life** [comment]
Nice 'n minimal 👍

**Comment by nutjob4life** [comment]
@edwardbarraza how do I get ahold of the NASA HDS theme for WordPress?

**Comment by nutjob4life** [comment]
@nutjob4life note to self; see https://developer.nasa.gov/nwmt/hds-wordpress/tree/preprod/themes

**Comment by edwardbarraza** [comment]
![ipda_logo_light.svg](https://images.zenhubusercontent.com/5ebddfad11d80c7b1f6e5d8d/5f565b04-8b21-48dc-8b62-0c9b7d7f55cb)![ipda_logo_dark.svg](https://images.zenhubusercontent.com/5ebddfad11d80c7b1f6e5d8d/89ff7e14-9204-48a0-82d6-aaff2541a94a)

**Comment by nutjob4life** [comment]
Added @edwardbarraza as an Administrator on the site.

**Comment by nutjob4life** [comment]
@edwardbarraza @jordanpadams the NASA HDS theme is now installed onto the site, but all content is now invisible. I don't suppose you know of any HDS experts who can advise? I'm tempted to go back to the "Marenda" theme.

**Comment by jordanpadams** [comment]
@nutjob4life we can just go with another theme for now. the HDS team is not accessible. the catch being I just want to make sure we adapt our color scheme to be appropriately accessible

**Comment by nutjob4life** [comment]
@jordanpadams I'm leave the NASA HDS theme active for now; maybe @edwardbarraza has an idea on how to work it?

**Comment by jordanpadams** [comment]
@nutjob4life unfortunately, no one on the team has any experience with Wordpress. so I think we are just going to have to drop it for now 😞

**Comment by nutjob4life** [comment]
Fair enough 😕

**Comment by jordanpadams** [comment]
@jordanpadams to review

**Comment by jordanpadams** [comment]
@nutjob4life can we update the "_IPDA_" links at the top and bottom of the page with the icon? Looks a little weird...

**Comment by nutjob4life** [comment]
> @nutjob4life can we update the "_IPDA_" links at the top and bottom of the page with the icon? Looks a little weird...

@jordanpadams by "icon" you mean the logo that @edwardbarraza created?

**Comment by jordanpadams** [comment]
@nutjob4life yes! Thanks!

**Comment by nutjob4life** [comment]
@jordanpadams will see if I can wedge it into those places, as soon as DSIO-3426 is fixed

**Comment by nutjob4life** [comment]
@jordanpadams done!

**Comment by jordanpadams** [comment]
@nutjob4life looks great! can we run another scan for accessibility?

also, one typo "discovery" -> "discover"

is there a login to wordpress somewhere so I could make updates in the future for silly things like that?

**Comment by nutjob4life** [comment]
@jordanpadams fixed the typo.

It looks like you have an account on the site already. I've had the site send you a password reset prompt. Let me know if the email doesn't show up.
