### ISSUE TITLE
Enable public access to Wordpress site for external review

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetarydata.org#18]
## 💡 Description

The site needs review from the IPDA SC so we need to get the site online.

Option 1: Work with SAs to get this put on some public VPC or on a pub domain we already have
Option 2: Proxy from planetarydata.org/beta

**Comment by jordanpadams** [comment]
@nutjob4life how feasible is option 2 from the current plone site and Wordpress config?

**Comment by jordanpadams** [comment]
DSIO-3850 submitted to investigate option 1

**Comment by tloubrieu-jpl** [comment]
The web site ipda.jpl.nasa.gov is online
