### ISSUE TITLE
As a member of the Europlanet Society, I would like my institution represented on the IPDA website

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/planetarydata.org#2]
The website for the International Planetary Data Alliance (IPDA) at https://planetarydata.org/ includes not just one but two member pages. One at https://planetarydata.org/about/member-institutions shows the Europlanet Society. However, the one at https://planetarydata.org/about/about-the-ipda/ does not.

As a member of the IPDA, and specifically as a member of the Europlanet Society, I would like to see my institution represented in both places.

**Comment by jordanpadams** [comment]
@nutjob4life is this still a needed update?

**Comment by nutjob4life** [comment]
Oh wow this was done years ago! Well, weeks at least, @jordanpadams. Closing this.
