### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/planetarydata.org#25]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

https://ipda.jpl.nasa.gov/meetings/

says

The IPDA 17th Steering Committee meeting was held at **ESCA** (Madrid, Spain) in September 2022.

ESCA -> ESAC

### 🕵️ Expected behavior

I expected [...]

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
Skipping I&T. Very simple fix. No additional testing needed.
