### ISSUE TITLE
Deploy WordPress in an EC2 instance in JPL Cloud

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetarydata.org#8]

**Comment by nutjob4life** [comment]
@jordanpadams Rojeh is wondering what the clearance number for planetarydata.org is.

I may be recalling (incorrectly) that we avoided the need for a clearance number due to the non `.jpl.nasa.gov` domain and/or the URS team never got back to us.

**Comment by jordanpadams** [comment]
@nutjob4life https://urs.jpl.nasa.gov/Document=URS304382 . It says it is under Expert Review, but I will forward them the email chain of them outright refusing to respond to emails/phone call communications.

**Comment by nutjob4life** [comment]
Thanks @jordanpadams. Rojeh is a pedantic stickler, a human immovable object—but I mean that in the nicest way. He's refused to allow my other projects to make any progress without clearance numbers. But in the nicest way. 

It's why I suggested we just find WordPress hosting elsewhere, like on Flywheel. The current gatekeeper? 😬 (nicest way)

**Comment by nutjob4life** [comment]
I can't believe it, but apparently (after over 6 months) we have a clearance number:

🎇 **CL#22-5090** 🎆

Rojeh has received this information [in this ticket](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-2682) along with a choice of a 1 gigabyte MySQL-based RDS instance. (The current Plone-based site uses ½ gigabyte.)

**Comment by nutjob4life** [comment]
@jordanpadams looks like we're stuck in the mud again. Thus speaketh Rojeh:

> The clearance mentions ipda.jpl.nasa.gov, which is not an external domain. The clearance does not include pds-ipda.jpl.nasa.gov or planetarydata.org, which are external domains. Will you please update the clearance to include the two external sites? I mention this because we are starting A&A on PDS and these will come up?

**Comment by jimmie** [comment]
Site is up on JPL AWS (private for now).

DSIO-2682 open to enable file uploads.

**Comment by jordanpadams** [comment]
@nutjob4life status: another permission issue identified with setup. email does not work for users outside JPL. DSIO-2775. texted temp password for time being.

up next: awaiting DSIO closeout and content migration.

**Comment by jimmie** [comment]
See #9 - blocked on Tom Stein (GEO)

**Comment by nutjob4life** [comment]
The URL is: http://pdscloud-ipda.jpl.nasa.gov
