### ISSUE TITLE
Migrate existing content from Plone to Wordpress

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetarydata.org#9]

**Comment by jimmie** [comment]
Waiting for Tom Stein (GEO) to take this over.

**Comment by jordanpadams** [comment]
@nutjob4life can we ping Tom (CC me) to see where we are at with this?

**Comment by jordanpadams** [comment]
or even just forward me the latest email chain and I can ping him

**Comment by nutjob4life** [comment]
Turns out Tom's over-subscribed so he's assigned me (by dint of saying "Sean would be more awesome at this") to populate the site with content using the attached slide deck.

[IPDA-web-site-newlook-v20221003.pptx](https://github.com/NASA-PDS/planetarydata.org/files/10128277/IPDA-web-site-newlook-v20221003.pptx)

**Comment by tloubrieu-jpl** [comment]
@nutjob4life @jordanpadams is this ticket still blocked ? If not, maybe someone else that Sean could add the slide deck to the site ?

**Comment by nutjob4life** [comment]
I will be tackling this during the next sprint

**Comment by tloubrieu-jpl** [comment]
@nutjob4life needs plugins and it takes some time to get them deployed by our SAs.

**Comment by tloubrieu-jpl** [comment]
Good progress on that, see https://pdscloud-ipda.jpl.nasa.gov/

**Comment by tloubrieu-jpl** [comment]
The new url https://ipda.jpl.nasa.gov/

**Comment by jordanpadams** [comment]
@nutjob4life looks great! let's maybe talk next week with @mpnewcom (if he is in), about some basically styling from the PDS WDS we should be using here. The only think I am really worried about with doing an entirely separate look-and-feel is the accessibility that comes out of the box. But if we have other ways of checking that, then that's OK too.

**Comment by nutjob4life** [comment]
The theme I chose claims to have WCAG AA and 508 adherence. But even so, accessibility can be affected by the content itself (for example, adding an image with no `alt` text). So scans should be done regardless.

I recommend [axe DevTools](https://www.deque.com/axe/devtools/). It's a browser extension that gives some nicely detailed reports. (There's a free trial.)

**Comment by tloubrieu-jpl** [comment]
Still broken images and 2 more sections to finalize the migration.

**Comment by nutjob4life** [comment]
@jordanpadams wrote in `<93C8F673-E347-4CC3-9066-6B06E2A4BDAB@jpl.nasa.gov>`:

> A couple of my nitpicks:
>  
> https://ipda.jpl.nasa.gov/access-to-data/ the diagrams are a bit small and hard to read. Maybe put them one on top of the other?
>
> The links for that page should really go to whatever is documented here: https://planetarydata.org/access-to-data
>
> Or in reality, those pages linked there to Atmospheres node should really be migrated to Wordpress as well. They should not be hosted at Atmospheres Node (ugh… why did they not just give them to us to put on pds.nasa.gov 😊 )
>  
> https://ipda.jpl.nasa.gov/partners/ cannot really read the name below the logos

**Comment by nutjob4life** [comment]
@jordanpadams thanks for the feedback!

- Stacked the diagrams as you suggested. The "solar system" is a lot easier to read now. Just a note that this could still get dinged as an accessibility issue. An image map looks neat but it isn't all that friendly. A simple list would get us a higher WCAG score
- Thanks for the links. I've added them.
- Yes, as soon as the Atmospheres node goes down, so does essentially that page! 😝
- I've removed the image captions altogether

**Comment by jordanpadams** [comment]
@nutjob4life 👍

**Comment by jordanpadams** [comment]
Status: awaiting inputs from Tom Stein and Christophe

**Comment by jimmie** [comment]
Will need to schedule a face to face (or screen to screen as it were) w/ Tom etal

**Comment by tloubrieu-jpl** [comment]
@nutjob4life will set up a meeting with Tom Stein

**Comment by nutjob4life** [comment]
@tloubrieu-jpl @jordanpadams if we're going to be changing the entire theme, perhaps we should do that first before showing it to Tom Stein? He might be in for a bit of a shock if he signs off on the current theme and suddenly sees HDS in its place later on.

**Comment by jordanpadams** [comment]
@nutjob4life I think I am going to close this as "done" for now. I think the design stuff from #15 is really blocking the review of the website and the overall closeout of https://github.com/nasa-pds/planetarydata.org/issues/7 . we can open additional tickets if we have more things we want to pull from Plone

**Comment by nutjob4life** [comment]
Sound reasoning, thanks @jordanpadams !
